-d E:\FPGA\picotiny\picotiny\impl\gwsynthesis\picotiny.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\FPGA\picotiny\picotiny\src\picotiny.cst
-cfg E:\FPGA\picotiny\picotiny\impl\pnr\device.cfg
-sdc E:\FPGA\picotiny\picotiny\src\picotiny.sdc
-bit
-tr
-ph
-timing
-cst_error
